### ISSUE TITLE
Issue with the latest version of Angular-IMask and Angular 13

### ISSUE THREAD

**Issue by bstaley** [uNmAnNeR/imaskjs#741]
**Describe the bug**
Ivy will not compile with the latest angular-imask

**To Reproduce**
[imask-test.zip](https://github.com/uNmAnNeR/imaskjs/files/9609113/imask-test.zip)
`npm i`
`npm run build:lib`

**Expected behavior**
The library builds with partial ivy compile in Angular 13

**Environment:**
 - OS: Windows 10
 - Browser: n/a

 - Version: n/a
 - IMask: 6.4.3
 - Framework/plugin version: angular-imask 6.4.3

**Additional context**
![image001](https://user-images.githubusercontent.com/2222437/191301838-0e5fc383-f240-4011-9dda-1085a30e76eb.png)

**Comment by prasetyodimas** [comment]
Please help me to, i got the issues same.

./node_modules/angular-imask/fesm2015/angular-imask.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string '/Users/dimasprasetyo/Documents/project/sbi/sabiweb-admin/node_modules/angular-imask/fesm2015/angular-imask.mjs: This application depends upon a library published using Angular version 14.2.2, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.

Environment:

OS: Mac Os
Browser: Chrome
Version Angular :  "@angular/core": "~13.0.0",
Framework/plugin version: "angular-imask": "^6.4.2",

<img width="1423" alt="Screen Shot 2022-10-25 at 10 09 10" src="https://user-images.githubusercontent.com/9084664/197673224-16fcb79c-0a64-460a-a3e0-3f855fce8a63.png">

**Comment by uNmAnNeR** [comment]
should be fixed in a89e1442ffc6e772a1eda6c447450f72ab9beed3

**Comment by mihailTheStudent** [comment]
Hi, @uNmAnNeR 
The bug is still reproduced 🙁
Currently load angular-imask v.6.4.3 and get the same error

![image](https://user-images.githubusercontent.com/90143649/220591007-c54f019e-9a22-46ef-90d2-e87c6cfdfa9b.png)

Angular version is ^13.0.0 (loaded 13.3.12)

Please, check, how to fix it.
